import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
interface LayoutProps {
    children: React.ReactNode;
}
let Pages = [
    {
        name: "todo",
        path: "/todo",
    },
    {
        name: "user",
        path: "/user",
    },
    {
        name: "RQ-user",
        path: "/RQ-user",
    },
    {
        name: "react-hook-form-trigger",
        path: "/react-hook-form-trigger",
    },
    {
        name: "simple-todo-app",
        path: "/simple-todo-app",
    },
    {
        name: "product-variants-version",
        path: "/product-variants-version",
    },
];

export default function RootLayout({ children }: LayoutProps) {
    return (
        <html lang="en" className="scroll-smooth  bg-white" data-lt-installed="true">
            <body>{children}</body>
        </html>
    );
}
